"""Cycloidal gear tooth geometry.

Ported from the CPG (Cycloidal Gear Profile Generator) reference — computes
the point cloud of a cycloidal gear tooth and returns the same per-segment
(left/right) arrays the involute generator produces, so the plotter,
DXF exporter and spec writer can be shared unchanged.

Cycloidal tooth geometry
------------------------
A cycloidal flank is the trace of a point on a *rolling circle* that rolls
without slipping on the pitch circle:

* an **epicycloid** is generated by rolling on the outside of the pitch
  circle and forms the addendum (tip-side) flank,
* a **hypocycloid** is generated by rolling on the inside of the pitch
  circle and forms the dedendum (root-side) flank.

Both share the rolling radius ``r = gen_ratio * m / 2``.  With the pitch
radius ``R`` and roll angle ``phi`` the two curves are

    epi :  x + iy = e^{iA} [(R + r) - r e^{i phi}]
    hypo:  x + iy = e^{-iA}[(R - r) + r e^{i phi}],   A = r phi / R

A tip round (radius ``E * m``) and a root round (radius ``C * m``) join the
flanks to the tip/root circles; the tooth is symmetric about its centre
line and arrayed ``z`` times around the gear.

The output segments use the same angular convention as the involute
generator: a root arc centred on the X axis (valley), teeth peaks at
``+-pi/z``, so ``plotter.generate`` and ``exporters.save_dxf`` accept them
unchanged.
"""

from __future__ import annotations

import math

import numpy as np

from .gear import GearParams, symmetry_y

TAU: float = 2.0 * math.pi
ROUND_PRECISION: int = 6


# ---------------------------------------------------------------- cycloid curves
def epicycloid(phi: np.ndarray, rp: float, r: float) -> np.ndarray:
    """Epicycloid points (Nx2): rolling circle radius ``r`` outside pitch ``rp``."""
    A = r * phi / rp
    return np.stack(
        [(rp + r) * np.cos(A) - r * np.cos(A + phi),
         (rp + r) * np.sin(A) - r * np.sin(A + phi)], axis=1)


def hypocycloid(phi: np.ndarray, rp: float, r: float) -> np.ndarray:
    """Hypocycloid points (Nx2): rolling circle radius ``r`` inside pitch ``rp``."""
    A = r * phi / rp
    return np.stack(
        [(rp - r) * np.cos(A) + r * np.cos(phi - A),
         -(rp - r) * np.sin(A) + r * np.sin(phi - A)], axis=1)


# ---------------------------------------------------------------- arc helpers
def arc_origin(rho: float, a0: float, a1: float, n: int = 32) -> np.ndarray:
    """Circular arc centred on the origin from angle ``a0`` to ``a1`` (Nx2)."""
    a = np.linspace(a0, a1, n)
    return np.stack([rho * np.cos(a), rho * np.sin(a)], axis=1)


def arc_center(C, rho: float, P0, P1, n: int = 24) -> np.ndarray:
    """Circular arc centred at ``C`` from the direction of ``P0`` to ``P1`` (Nx2)."""
    a0 = math.atan2(P0[1] - C[1], P0[0] - C[0])
    a1 = math.atan2(P1[1] - C[1], P1[0] - C[0])
    while a1 - a0 > math.pi:
        a1 -= TAU
    while a1 - a0 < -math.pi:
        a1 += TAU
    a = np.linspace(a0, a1, n)
    return np.stack([C[0] + rho * np.cos(a), C[1] + rho * np.sin(a)], axis=1)


def rot_pts(P: np.ndarray, th: float) -> np.ndarray:
    """Rotate Nx2 point array by angle ``th`` (counter-clockwise)."""
    c, s = math.cos(th), math.sin(th)
    return P @ np.array([[c, s], [-s, c]])


# ---------------------------------------------------------------- fillets
def fillet(P: np.ndarray, rho: float, centre_radius: float,
           r_circle: float, side: int = 1):
    """Tangent fillet of radius ``rho`` between curve ``P`` and circle ``r_circle``.

    ``P`` runs pitch-point -> flank end over the FULL flank so the tangency
    always exists on the correct side.  Returns a dict with tangency data or
    ``None`` when the fillet cannot be built.
    """
    if rho is None or rho <= 0 or len(P) < 4:
        return None
    d = np.zeros_like(P)
    v = P[2:] - P[:-2]
    d[1:-1] = v / np.linalg.norm(v, axis=1, keepdims=True)
    d[0], d[-1] = d[1], d[-2]
    nrm = side * np.stack([-d[:, 1], d[:, 0]], axis=1)
    C = P + rho * nrm
    g = np.hypot(C[:, 0], C[:, 1]) - centre_radius
    for i in range(len(P) - 1, 0, -1):
        if g[i - 1] * g[i] < 0:
            t = g[i - 1] / (g[i - 1] - g[i])
            Cc = C[i - 1] + t * (C[i] - C[i - 1])
            n = nrm[i - 1] + t * (nrm[i] - nrm[i - 1])
            n = n / np.linalg.norm(n)
            u = Cc / np.linalg.norm(Cc)
            Cc = centre_radius * u
            Pt = Cc - rho * n
            Pc = r_circle * u
            return {"cut": i, "Pt": Pt, "C": Cc, "Pc": Pc}
    return None


def fit_round(P, rho, centre_radius, r_circle, th_limit, is_tip):
    """Shrink a round radius ``rho`` until its tangency fits the tooth."""
    rho_eff = rho
    f = None
    for _ in range(40):
        if rho_eff <= 1e-9:
            break
        f = fillet(P, rho_eff, centre_radius, r_circle, side=+1)
        if f is None:
            break
        a = math.atan2(f["Pc"][1], f["Pc"][0])
        if (a < th_limit) if is_tip else (a > th_limit):
            break
        rho_eff *= 0.85
        centre_radius = (r_circle - rho_eff) if is_tip else (r_circle + rho_eff)
    return rho_eff, f


# ---------------------------------------------------------------- tooth build
def build_cycloid(p: GearParams) -> dict:
    """Build the cycloid half-tooth segments in involute-compatible form.

    Returns a ``segments`` dict with the same keys the involute path uses:
    ``root_arc, root_round, flank, tip_round, tip_arc`` each a ``(x, y)``
    array pair describing the RIGHT half of the tooth (from the root arc at
    the valley up to the tip arc at the tooth peak ``+pi/z``), plus the
    reference radii.
    """
    z, m = p.z, p.m
    X, B, A, D, C, E = p.x, p.b, p.a, p.d, p.c, p.e

    alpha_m = np.pi / z
    zeff = z + 2.0 * X
    t_half = (np.pi / 2.0 - B) / zeff

    rp = m * (z / 2 + X)
    r = 0.5 * p.gen_ratio * m
    r_tip = rp + A * m
    r_root = rp - D * m
    re = E * m
    rc = C * m

    if r_root <= 0:
        raise ValueError("Too few teeth (root circle radius <= 0).")
    if rp <= r:
        raise ValueError("Rolling circle too large (pitch radius must exceed it).")
    if r_tip > rp + 2 * r:
        raise ValueError("Rolling circle too small (tip circle unreachable: increase gen_ratio).")
    if r_root < rp - 2 * r:
        raise ValueError("Rolling circle too small (root circle unreachable: increase gen_ratio).")
    if re >= A * m:
        raise ValueError("Tip round radius exceeds the addendum.")
    if rc >= D * m:
        raise ValueError("Root round radius exceeds the dedendum.")

    cos_t = ((rp + r) ** 2 + r ** 2 - r_tip ** 2) / (2 * r * (rp + r))
    phi_tip = float(np.arccos(np.clip(cos_t, -1.0, 1.0)))
    s2 = (rp ** 2 - r_root ** 2) / (4 * r * (rp - r))
    phi_root = 2.0 * float(np.arcsin(np.sqrt(np.clip(s2, 0.0, 1.0))))

    n = p.seg_involute
    th_space = -t_half
    th_tooth = t_half

    epi = epicycloid(np.linspace(0.0, phi_tip, n), rp, r)
    hypo = hypocycloid(np.linspace(0.0, phi_root, n), rp, r)

    re_eff, ft = fit_round(epi, re, r_tip - re, r_tip, th_tooth, True)
    rc_eff, fr = fit_round(hypo, rc, r_root + rc, r_root, th_space, False)

    if fr:
        a_c = math.atan2(fr["Pc"][1], fr["Pc"][0])
        root_arc = arc_origin(r_root, th_space, a_c, p.seg_root)
        root_round = arc_center(fr["C"], rc_eff, fr["Pc"], fr["Pt"], p.seg_root_r)
        flank = np.vstack([hypo[:fr["cut"]], fr["Pt"]])[::-1]
    else:
        a_c = math.atan2(hypo[-1][1], hypo[-1][0])
        root_arc = arc_origin(r_root, th_space, a_c, p.seg_root)
        root_round = np.empty((0, 2))
        flank = hypo[::-1]

    if ft:
        tip_flank = np.vstack([epi[:ft["cut"]], ft["Pt"]])
        a_t = math.atan2(ft["Pc"][1], ft["Pc"][0])
        tip_round = arc_center(ft["C"], re_eff, ft["Pt"], ft["Pc"], p.seg_edge_r)
        tip_arc = arc_origin(r_tip, a_t, th_tooth, p.seg_outer)
    else:
        tip_flank = epi
        tip_round = np.empty((0, 2))
        tip_arc = arc_origin(r_tip, math.atan2(epi[-1][1], epi[-1][0]),
                             th_tooth, p.seg_outer)

    # Align so the tooth peak sits exactly at +pi/z (the involute convention).
    align = alpha_m - t_half

    def _pair(pts: np.ndarray):
        return pts[:, 0], pts[:, 1]

    segment = {
        "root_arc": _pair(rot_pts(root_arc, align)),
        "root_round": _pair(rot_pts(root_round, align)),
        "flank": _pair(rot_pts(np.vstack([flank, tip_flank]), align)),
        "tip_round": _pair(rot_pts(tip_round, align)),
        "tip_arc": _pair(rot_pts(tip_arc, align)),
    }
    return {
        "segments": segment,
        "rp": rp,
        "r_tip": r_tip,
        "r_root": r_root,
    }


def cycloid_artifacts(p: GearParams) -> dict:
    """Full per-segment arrays compatible with the involute plotter/DXF path."""
    built = build_cycloid(p)
    seg = built["segments"]
    rp = built["rp"]
    r_tip = built["r_tip"]
    r_root = built["r_root"]

    arc_r = seg["root_arc"]
    root_r = seg["root_round"]
    inv_r = seg["flank"]
    edge_r = seg["tip_round"]
    outer_r = seg["tip_arc"]

    arc_l = symmetry_y(*arc_r)
    root_l = symmetry_y(*root_r)
    inv_l = symmetry_y(*inv_r)
    edge_l = symmetry_y(*edge_r)
    outer_l = symmetry_y(*outer_r)

    offset_dia = 2.0 * rp
    outer_dia = 2.0 * r_tip
    root_dia = 2.0 * r_root

    return {
        "inv_r": inv_r, "inv_l": inv_l,
        "edge_r": edge_r, "edge_l": edge_l,
        "root_r": root_r, "root_l": root_l,
        "outer_r": outer_r, "outer_l": outer_l,
        "arc_r": arc_r, "arc_l": arc_l,
        "align_angle": np.pi / 2 - np.pi / p.z,
        "p_angle": 2 * np.pi / p.z,
        "base_dia": None,
        "pitch_dia": p.m * p.z,
        "offset_dia": offset_dia,
        "outer_dia": outer_dia,
        "root_dia": root_dia,
    }